# Generated by Django 5.2.7 on 2026-02-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='active or not active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name='price')),
                ('short_description', models.CharField(max_length=300, null=True, verbose_name='short description')),
                ('description', models.TextField(verbose_name='main description')),
                ('is_active', models.BooleanField(default=False, verbose_name='active or is not active')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True)),
                ('is_delete', models.BooleanField(verbose_name='is delete or not')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='products')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=100, verbose_name='caption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductTags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'productTag',
                'verbose_name_plural': 'productTags',
            },
        ),
    ]
