# Generated by Django 5.2.11 on 2026-02-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_productinformation_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='tag title')),
            ],
            options={
                'verbose_name': 'productTag',
                'verbose_name_plural': 'productTags',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productinformation',
            options={'verbose_name': 'productInformation', 'verbose_name_plural': 'productInformations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_information', to='product_module.productinformation', verbose_name='اطلاعات تکمیلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_tags', to='product_module.producttag', verbose_name='product tags'),
        ),
    ]
