# Generated by Django 5.2.7 on 2026-06-04 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی لینک های فوتر',
                'verbose_name_plural': 'دسته بندی های لینک های فوتر',
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us_text',
            field=models.TextField(verbose_name='متن درباره ی ما سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(max_length=200, verbose_name='آدرس '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.TextField(max_length=200, verbose_name='متن کپی رایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن '),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_url',
            field=models.CharField(max_length=200, verbose_name='دامنه سایت'),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_module.footerlinkbox', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': ' لینک فوتر',
                'verbose_name_plural': ' لینک های فوتر',
            },
        ),
    ]
