# Generated by Django 5.2.7 on 2026-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_slider_is_active_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.URLField(verbose_name='عنوان لینک'),
        ),
    ]
